name: bash_unit tests
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install ShellCheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
    - name: Lint shell scripts with ShellCheck
      run: |
        shellcheck --norc --exclude=SC1091 -S info -P SCRIPTDIR -P . -f gcc $(git ls-files '*.sh' '*.bash' '*.bashrc' '*.bash_aliases' '*.bash_profile' 'bash_unit')
    - name: Unit testing with bash_unit
      run: |
        curl -s https://raw.githubusercontent.com/bash-unit/bash_unit/master/install.sh | bash
        shopt -s nullglob
        for spec_file in spec/test-*; do
          FORCE_COLOR=true timeout 15 ./bash_unit "$spec_file"
          status=$?

          if [ $status -eq 124 ]; then
            echo "::error::Timeout failure: $spec_file exceeded 15 seconds"
            exit 124
          fi

          if [ $status -ne 0 ]; then
            echo "::error::Test failure: $spec_file exited with status $status"
            exit $status
          fi
        done